#=======================================================
# fmtmlf.awk for Speech Separation Challenge
# 
# Parse HTK MLF files (generated by HVite with "-o ST")
# to produce recognition results with a format of:
# <filename    colour letter number> for speech shape noise
# e.g.
#
# s10_bgad7s    g d 7
# s10_brav8p    r v 8
#
#
# Ning Ma, Sheffield University
# 19 Feb 2006
#=======================================================

BEGIN { FS = "[/.]"; }
/rec/ { printf("%s    ",$(NF-1)); }
$0 == "." { printf("\n"); }
$0 == "one" { printf("1 "); }
$0 == "two" { printf("2 "); }
$0 == "three" { printf("3 "); }
$0 == "four" { printf("4 "); }
$0 == "five" { printf("5 "); }
$0 == "six" { printf("6 "); }
$0 == "seven" { printf("7 "); }
$0 == "eight" { printf("8 "); }
$0 == "nine" { printf("9 "); }
$0 == "zero" { printf("z "); }
/^[a-z]/ { if (length($0)==1) printf("%s ",$0); }

